[package]
name = "arbi-mango-bot1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { version = "1.14.1", features = ["rt-multi-thread", "time", "macros", "sync"] }
jsonrpsee = { version = "0.17.0", features = ["macros", "http-client"] }
reqwest = { version = "0.11.17", features = ["json"] }
serde = "1.0.141"
serde_json = "1.0.82"
