[package]
name = "arbi-mango-bot1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { version = "1.14.1", features = ["rt-multi-thread", "time", "macros", "sync"] }
tokio-tungstenite = { version = "0.17.2" }
futures = "0.3"
url = "2.3.1"

reqwest = { version = "0.11.17", features = ["json"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.82"
