[package]
name = "arbi-mango-bot1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.14.1", features = ["rt-multi-thread", "time", "macros", "sync"] }
jsonrpsee = { version = "0.17.0", features = ["macros", "http-client"] }
